### ISSUE TITLE
Python? Django?

### ISSUE THREAD

**Issue by nikodrupal** [13werwolf13/TechSupTeleBot#1]
Здравствуйте, Дмитрий!
Сразу хочу извиниться, что пишу вам в гитхаб в issue.
Я ищу разработчика с опытом в Python (который у вас есть, судя по репозиторию :), хотя бы небольшим опытом в Django, возможностью разговаривать хотя бы на ломаном английском и суммарным опытом программирования от 2 до 100 лет :)
Напишите, пожалуйста, в скайп cv.kulikov@gmail.com (это именно скайп), если это про вас :)
Спасибо

**Comment by 13werwolf13** [comment]
1) я не разу не прогер
2) если вы посмотрите мой код вы поймёте что я ничего не умею
3) в 2017 году пользоваться скайпом?!
4) джанго даже не тыкал ибо не хочу в веб
